/**
 * APPU voice controller.
 * Speech audio is generated by the n8n workflow and returned with each reply.
 * This client only handles microphone input, playback, subtitles, and sound cues.
 */
class VoiceEngine {
    static isVoiceSupported() {
        const hasRecognition = typeof window !== 'undefined' && Boolean(window.SpeechRecognition || window.webkitSpeechRecognition);
        const hasMediaDevices = typeof navigator !== 'undefined' && Boolean(navigator.mediaDevices && typeof navigator.mediaDevices.getUserMedia === 'function');
        return Boolean(hasRecognition && hasMediaDevices);
    }

    static get VOICE_MESSAGES() {
        return {
            en: {
                unsupported: "Voice isn't available on this screen — tap 'Type instead' to chat",
                permissionDenied: "Microphone access was denied. Please allow microphone permissions or tap 'Type instead' to chat.",
                noMic: "No microphone found on this device. Tap 'Type instead' to chat.",
                micUnavailableLabel: "Voice unavailable"
            },
            kn: {
                unsupported: "ಈ ಪರದೆಯಲ್ಲಿ ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ — ಚಾಟ್ ಮಾಡಲು 'ಬರೆಯಿರಿ' ಟ್ಯಾಪ್ ಮಾಡಿ",
                permissionDenied: "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಅನುಮತಿ ನೀಡಿ ಅಥವಾ 'ಬರೆಯಿರಿ' ಟ್ಯಾಪ್ ಮಾಡಿ.",
                noMic: "ಈ ಸಾಧನದಲ್ಲಿ ಮೈಕ್ರೊಫೋನ್ ಕಂಡುಬಂದಿಲ್ಲ. ಚಾಟ್ ಮಾಡಲು 'ಬರೆಯಿರಿ' ಟ್ಯಾಪ್ ಮಾಡಿ.",
                micUnavailableLabel: "ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ"
            },
            hi: {
                unsupported: "इस स्क्रीन पर वॉइस उपलब्ध नहीं है — चैट करने के लिए 'टाइप करें' पर टैप करें",
                permissionDenied: "माइक्रोफ़ोन अनुमति अस्वीकृत है। कृपया ब्राउज़र में अनुमति दें या 'टाइप करें' पर टैप करें.",
                noMic: "इस डिवाइस पर कोई माइक्रोफ़ोन नहीं मिला। 'टाइप करें' पर टैप करें.",
                micUnavailableLabel: "वॉइस अनुपलब्ध"
            }
        };
    }

    getLocalizedVoiceNotice(type) {
        const lang = this.currentLanguage || 'en';
        const dict = VoiceEngine.VOICE_MESSAGES[lang] || VoiceEngine.VOICE_MESSAGES.en;
        if (type === 'unsupported') return dict.unsupported;
        if (type === 'permission-denied') return dict.permissionDenied;
        if (type === 'no-mic') return dict.noMic;
        if (type === 'micUnavailableLabel') return dict.micUnavailableLabel;
        return dict.unsupported;
    }

    constructor(options = {}) {
        this.onSpeechStart = options.onSpeechStart || (() => {});
        this.onSpeechEnd = options.onSpeechEnd || (() => {});
        this.onListeningStart = options.onListeningStart || (() => {});
        this.onListeningEnd = options.onListeningEnd || (() => {});
        this.onTranscript = options.onTranscript || (() => {});
        this.onInterimTranscript = options.onInterimTranscript || (() => {});
        this.onVoiceUnavailable = options.onVoiceUnavailable || (() => {});
        this.onPermissionDenied = options.onPermissionDenied || (() => {});

        this.soundEnabled = true;
        this.autoSpeak = true;
        this.rate = 1;
        this.currentLanguage = 'en';
        this.isListening = false;
        this.isSpeaking = false;
        this.awaitingResponse = false;
        this.liveSessionActive = false;
        this.subtitleTimer = null;
        this.audioContext = null;
        this.isVoiceSupported = VoiceEngine.isVoiceSupported();

        this.micButton = document.getElementById('btn-mic');
        this.micLabel = document.querySelector('.mic-label');
        this.subtitleElement = document.getElementById('subtitles-text');
        this.equalizer = document.querySelector('.equalizer');
        this.audioPlayer = new Audio();
        this.audioPlayer.id = 'appu-audio-player';
        this.audioPlayer.hidden = true;
        this.audioPlayer.preload = 'auto';
        this.audioPlayer.volume = 1.0;
        this.audioPlayer.muted = false;
        document.body.appendChild(this.audioPlayer);

        this.initAudioPlayerEvents();
        this.initSpeechRecognition();
    }

    initAudioPlayerEvents() {
        this.audioPlayer.addEventListener('play', () => {
            this.isSpeaking = true;
            if (this.recognition) {
                try { this.recognition.abort(); } catch {}
            }
            this.updateSpeakingUI(true);
            this.onSpeechStart();
        });
        this.audioPlayer.addEventListener('ended', () => this.handleSpeechFinish());
        this.audioPlayer.addEventListener('error', () => {
            this.streamSubtitles('I could not play that answer. You can still read it here.');
            this.handleSpeechFinish();
        });
    }

    handleSpeechFinish() {
        this.awaitingResponse = false;
        this.isSpeaking = false;
        this.updateSpeakingUI(false);
        this.onSpeechEnd();
        if (this.liveSessionActive && !this.isListening) {
            window.setTimeout(() => this.startListening(), 350);
        }
    }

    setPlaybackRate(value) {
        const parsed = Number.parseFloat(value);
        this.rate = Number.isFinite(parsed) ? Math.min(1.35, Math.max(0.75, parsed)) : 1;
        this.audioPlayer.playbackRate = this.rate;
    }

    initWebAudio() {
        if (!this.audioContext) {
            const AudioContext = window.AudioContext || window.webkitAudioContext;
            if (AudioContext) this.audioContext = new AudioContext();
        }
        if (this.audioContext?.state === 'suspended') this.audioContext.resume();
    }

    playTone(frequency, duration = 0.08, volume = 0.04, type = 'sine') {
        if (!this.soundEnabled) return;
        this.initWebAudio();
        if (!this.audioContext) return;
        const oscillator = this.audioContext.createOscillator();
        const gain = this.audioContext.createGain();
        oscillator.type = type;
        oscillator.frequency.value = frequency;
        gain.gain.setValueAtTime(volume, this.audioContext.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.0001, this.audioContext.currentTime + duration);
        oscillator.connect(gain).connect(this.audioContext.destination);
        oscillator.start();
        oscillator.stop(this.audioContext.currentTime + duration);
    }

    playListenStart() {
        this.playTone(520, 0.08);
        window.setTimeout(() => this.playTone(720, 0.1), 70);
    }

    playListenStop() { this.playTone(420, 0.1); }
    playClick() { this.playTone(620, 0.05, 0.025); }
    playMessage() { this.playTone(760, 0.08, 0.03); }

    playSuccess() {
        [520, 660, 820].forEach((tone, index) => {
            window.setTimeout(() => this.playTone(tone, 0.12, 0.035), index * 90);
        });
    }

    toggleSound() {
        this.soundEnabled = !this.soundEnabled;
        if (this.soundEnabled) this.playClick();
        return this.soundEnabled;
    }

    initSpeechRecognition() {
        const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
        const hasMediaDevices = typeof navigator !== 'undefined' && Boolean(navigator.mediaDevices && typeof navigator.mediaDevices.getUserMedia === 'function');
        this.isVoiceSupported = Boolean(Recognition && hasMediaDevices);

        if (!this.isVoiceSupported || !Recognition) {
            this.recognition = null;
            this.applyVoiceUnavailableState();
            return;
        }

        this.recognition = new Recognition();
        this.recognition.continuous = false;
        this.recognition.interimResults = true;
        this.recognition.lang = 'en-IN';

        this.recognition.onstart = () => {
            this.isListening = true;
            this.lastErrorFatal = false;
            this._cycleStart = Date.now();
            this._cycleGotSpeech = false;
            this.updateLiveSessionUI();
            this.playListenStart();
            this.streamSubtitles('Listening — tell me what you want to learn.');
            this.onListeningStart();
        };

        this.recognition.onresult = event => {
            let finalText = '';
            let interimText = '';
            for (let index = event.resultIndex; index < event.results.length; index += 1) {
                const text = event.results[index][0].transcript;
                if (event.results[index].isFinal) finalText += text;
                else interimText += text;
            }
            if (interimText || finalText) this._cycleGotSpeech = true;
            if (interimText) this.onInterimTranscript(interimText.trim());
            if (finalText) {
                this.awaitingResponse = true;
                if (this.recognition) {
                    try { this.recognition.abort(); } catch {}
                }
                this.onTranscript(finalText.trim());
            }
        };

        this.recognition.onerror = event => {
            this.isListening = false;
            // 'no-speech' just means the engine timed out waiting for the user to start
            // talking (expected during natural pauses in a live session) -- not fatal.
            // 'aborted' happens when we stop it ourselves. Anything else (permission
            // denied, no mic, network) means retrying immediately would just loop forever.
            this.lastErrorFatal = event.error !== 'no-speech' && event.error !== 'aborted';
            if (this.lastErrorFatal) {
                this.awaitingResponse = false;
            }
            this.updateLiveSessionUI();
            if (event.error === 'not-allowed' || event.error === 'service-not-allowed') {
                this.stopLiveSession();
                const notice = this.getLocalizedVoiceNotice('permission-denied');
                this.streamSubtitles(notice);
                this.onPermissionDenied(notice);
                return;
            }
            if (event.error === 'audio-capture') {
                this.stopLiveSession();
                const notice = this.getLocalizedVoiceNotice('no-mic');
                this.streamSubtitles(notice);
                this.onVoiceUnavailable(notice);
                return;
            }
            if (this.lastErrorFatal) {
                this.streamSubtitles('I missed that. Tap the microphone and try again.');
            }
        };

        this.recognition.onend = () => {
            this.isListening = false;
            this.updateLiveSessionUI();
            this.onListeningEnd();
            // Some devices (seen on certain Android Chrome builds) end recognition almost
            // instantly without capturing anything. Auto-restarting then produces a rapid
            // on/off/on/off flicker loop. Detect these empty, sub-second cycles and, after a
            // few in a row, stop the live session gracefully instead of looping forever.
            // Rate-limit restarts: on some devices recognition ends almost instantly and the
            // auto-restart produces a rapid on/off/on/off flicker loop. Count short (<900ms)
            // cycles in a 4s window — regardless of whether brief noise triggered interim
            // results — and if too many happen, stop gracefully instead of looping forever.
            const now = Date.now();
            const cycleMs = now - (this._cycleStart || 0);
            this._restartTimes = (this._restartTimes || []).filter((t) => now - t < 4000);
            if (cycleMs < 900) this._restartTimes.push(now);
            if (this._restartTimes.length >= 4) {
                this._restartTimes = [];
                this.stopLiveSession();
                this.streamSubtitles("Voice had trouble starting on this device. Tap the mic to try again, or use “Type instead”.");
                return;
            }
            // Browsers stop listening after every pause even in a "live session" (there is
            // no true continuous mode cross-browser) -- restart automatically so the user
            // doesn't have to re-tap the mic between sentences, like a live conversation.
            if (this.liveSessionActive && !this.isSpeaking && !this.awaitingResponse && !this.lastErrorFatal) {
                window.setTimeout(() => this.startListening(), 400);
            }
        };
    }

    applyVoiceUnavailableState() {
        if (this.micButton) {
            this.micButton.classList.add('recognition-unavailable', 'voice-unavailable');
            this.micButton.setAttribute('aria-disabled', 'true');
            this.micButton.setAttribute('title', this.getLocalizedVoiceNotice('unsupported'));
        }
        if (this.micLabel) {
            const unavail = this.getLocalizedVoiceNotice('micUnavailableLabel');
            this.micLabel.dataset.idleLabel = unavail;
            this.micLabel.textContent = unavail;
        }
        if (typeof document !== 'undefined') {
            const controlDock = document.querySelector('.control-dock');
            if (controlDock) controlDock.classList.add('voice-unsupported');
            const btnChatMic = document.getElementById('btn-chat-mic');
            if (btnChatMic) {
                btnChatMic.classList.add('voice-unavailable');
                btnChatMic.style.display = 'none';
            }
        }
        this.onVoiceUnavailable(this.getLocalizedVoiceNotice('unsupported'));
    }

    setLanguage(language) {
        if (language === 'kn') {
            this.currentLanguage = 'kn';
            if (this.recognition) this.recognition.lang = 'kn-IN';
        } else if (language === 'hi') {
            this.currentLanguage = 'hi';
            if (this.recognition) this.recognition.lang = 'hi-IN';
        } else {
            this.currentLanguage = 'en';
            if (this.recognition) this.recognition.lang = 'en-IN';
        }
        if (!this.isVoiceSupported) {
            if (this.micLabel) {
                const unavail = this.getLocalizedVoiceNotice('micUnavailableLabel');
                this.micLabel.dataset.idleLabel = unavail;
                this.micLabel.textContent = unavail;
            }
            if (this.micButton) {
                this.micButton.setAttribute('title', this.getLocalizedVoiceNotice('unsupported'));
            }
        }
    }

    toggleLiveSession() {
        this.initWebAudio();
        if (!this.isVoiceSupported || !this.recognition) {
            const notice = this.getLocalizedVoiceNotice('unsupported');
            this.streamSubtitles(notice);
            this.onVoiceUnavailable(notice);
            return;
        }
        if (this.liveSessionActive) this.stopLiveSession();
        else this.startLiveSession();
    }

    startLiveSession() {
        if (!this.isVoiceSupported || !this.recognition) {
            const notice = this.getLocalizedVoiceNotice('unsupported');
            this.streamSubtitles(notice);
            this.onVoiceUnavailable(notice);
            return;
        }
        this.liveSessionActive = true;
        this.startListening();
    }

    stopLiveSession() {
        this.liveSessionActive = false;
        this.awaitingResponse = false;
        this.stopListening();
        this.stopSpeaking();
        this.updateLiveSessionUI();
    }

    startListening() {
        if (!this.recognition || this.isListening || this.isSpeaking || this.awaitingResponse) return;
        try {
            this.recognition.start();
        } catch (error) {
            if (error.name !== 'InvalidStateError') console.warn('Speech recognition could not start.', error);
        }
    }

    stopListening() {
        if (!this.recognition || !this.isListening) return;
        this.recognition.stop();
        this.playListenStop();
    }

    updateLiveSessionUI() {
        if (!this.micButton) return;
        this.micButton.classList.toggle('active', this.liveSessionActive || this.isListening);
        this.micButton.setAttribute('aria-pressed', String(this.liveSessionActive));
        this.micButton.setAttribute('aria-label', this.liveSessionActive ? 'Stop listening' : 'Tap to speak to Appu');
        if (this.micLabel) {
            const idleLabel = this.micLabel.dataset.idleLabel || 'Tap to speak';
            this.micLabel.textContent = this.liveSessionActive ? 'Listening now' : idleLabel;
        }
    }

    updateSpeakingUI(speaking) {
        document.body.classList.toggle('appu-speaking', speaking);
        if (this.equalizer) this.equalizer.classList.toggle('active', speaking);
    }

    async playBackendAudio(audioSource, text = '') {
        const contract = window.AppuVoiceContract;
        const source = contract?.toAudioSource ? contract.toAudioSource(audioSource) : audioSource;
        if (!source || !this.autoSpeak) {
            if (text) this.streamSubtitles(text);
            this.awaitingResponse = false;
            this.onSpeechEnd();
            if (this.liveSessionActive && !this.isListening) {
                window.setTimeout(() => this.startListening(), 350);
            }
            return false;
        }

        this.stopSpeaking();
        if (text) this.streamSubtitles(text);
        this.audioPlayer.src = source;
        this.audioPlayer.playbackRate = this.rate;
        this.audioPlayer.volume = 1.0;
        this.audioPlayer.muted = false;
        try {
            await this.audioPlayer.play();
            return true;
        } catch (error) {
            console.warn('Backend audio playback was blocked.', error);
            this.streamSubtitles(text || 'Tap the mic again to hear the answer.');
            this.handleSpeechFinish();
            return false;
        }
    }

    /**
     * Staging Streaming Audio Playback using fetch() with Bearer Authentication.
     * Streams chunked MP3 from the server-authorized endpoint.
     */
    async playStream(streamUrl, text = '', accessToken = '') {
        if (!streamUrl || !this.autoSpeak) {
            if (text) this.streamSubtitles(text);
            this.awaitingResponse = false;
            this.onSpeechEnd();
            if (this.liveSessionActive && !this.isListening) {
                window.setTimeout(() => this.startListening(), 350);
            }
            return false;
        }

        // Defensive resolution against configured APPU backend API origin
        let resolvedUrl = null;
        if (typeof AppuBackendClient !== 'undefined' && typeof AppuBackendClient.resolveAudioStreamUrl === 'function') {
            resolvedUrl = AppuBackendClient.resolveAudioStreamUrl(streamUrl);
        } else if (typeof streamUrl === 'string' && streamUrl.trim()) {
            const trimmed = streamUrl.trim();
            const base = (typeof APPU_CONFIG !== 'undefined' && APPU_CONFIG.apiBaseUrl)
                ? APPU_CONFIG.apiBaseUrl.replace(/\/+$/, '')
                : 'https://api.appuai.online';
            if (trimmed.startsWith('/')) {
                resolvedUrl = `${base}${trimmed}`;
            } else {
                try {
                    const parsed = new URL(trimmed);
                    if (parsed.origin === new URL(base).origin) {
                        resolvedUrl = parsed.toString();
                    }
                } catch {}
            }
        }

        if (!resolvedUrl) {
            console.warn('Audio stream URL is invalid or blocked for security:', streamUrl);
            if (text) this.streamSubtitles(text);
            this.onSpeechEnd();
            return false;
        }

        this.stopSpeaking();
        if (text) this.streamSubtitles(text);

        try {
            this.currentStreamController = (typeof AbortController !== 'undefined') ? new AbortController() : null;
            const headers = {};
            if (accessToken && typeof accessToken === 'string' && accessToken.trim()) {
                headers['Authorization'] = `Bearer ${accessToken.trim()}`;
            } else if (typeof AppuBackendClient !== 'undefined' && typeof AppuBackendClient.getStoredGuestToken === 'function') {
                const guestToken = AppuBackendClient.getStoredGuestToken();
                if (guestToken) {
                    headers['X-Guest-Session-Token'] = guestToken;
                }
            }

            const fetchOpts = { method: 'GET', headers };
            if (this.currentStreamController) {
                fetchOpts.signal = this.currentStreamController.signal;
            }

            const response = await fetch(resolvedUrl, fetchOpts);
            if (!response.ok) {
                console.warn('Authenticated audio stream request failed', response.status);
                this.handleSpeechFinish();
                return false;
            }

            if (window.MediaSource && MediaSource.isTypeSupported('audio/mpeg')) {
                const mediaSource = new MediaSource();
                const objectUrl = URL.createObjectURL(mediaSource);
                this.audioPlayer.src = objectUrl;
                this.audioPlayer.playbackRate = this.rate;
                this.audioPlayer.volume = 1.0;
                this.audioPlayer.muted = false;

                const MIN_STARTUP_BUFFER_SECS = 1.2; // Initial buffer cushion to eliminate mid-speech chunk jitter pauses

                mediaSource.addEventListener('sourceopen', async () => {
                    let sourceBuffer;
                    try {
                        sourceBuffer = mediaSource.addSourceBuffer('audio/mpeg');
                    } catch (e) {
                        return;
                    }

                    let isDisposed = false;
                    let hasStartedPlayback = false;
                    let isAppending = false;
                    let streamDone = false;
                    const chunkQueue = [];

                    if (this.currentStreamController) {
                        this.currentStreamController.signal.addEventListener('abort', () => {
                            isDisposed = true;
                            chunkQueue.length = 0;
                            try {
                                if (mediaSource.readyState === 'open' && !sourceBuffer.updating) {
                                    mediaSource.endOfStream();
                                }
                            } catch {}
                        });
                    }

                    const checkAndStartPlayback = () => {
                        if (hasStartedPlayback || isDisposed) return;
                        let bufferedSecs = 0;
                        try {
                            if (sourceBuffer && sourceBuffer.buffered && sourceBuffer.buffered.length > 0) {
                                bufferedSecs = sourceBuffer.buffered.end(sourceBuffer.buffered.length - 1) - sourceBuffer.buffered.start(0);
                            }
                        } catch {}

                        // Start playback once initial threshold is satisfied OR stream has finished downloading
                        if (bufferedSecs >= MIN_STARTUP_BUFFER_SECS || (streamDone && chunkQueue.length === 0)) {
                            hasStartedPlayback = true;
                            this.audioPlayer.play().catch(e => {
                                if (!isDisposed) console.warn('Stream play error:', e);
                            });
                        }
                    };

                    const processQueue = () => {
                        if (isDisposed || mediaSource.readyState !== 'open' || !sourceBuffer) return;
                        if (isAppending || sourceBuffer.updating) return;

                        if (chunkQueue.length > 0) {
                            const nextChunk = chunkQueue.shift();
                            try {
                                isAppending = true;
                                sourceBuffer.appendBuffer(nextChunk);
                            } catch (err) {
                                isAppending = false;
                                console.warn('SourceBuffer append error:', err);
                            }
                            return;
                        }

                        checkAndStartPlayback();

                        if (streamDone && !sourceBuffer.updating && mediaSource.readyState === 'open') {
                            try {
                                mediaSource.endOfStream();
                            } catch {}
                        }
                    };

                    sourceBuffer.addEventListener('updateend', () => {
                        isAppending = false;
                        checkAndStartPlayback();
                        processQueue();
                    });

                    sourceBuffer.addEventListener('error', (err) => {
                        isAppending = false;
                        console.warn('SourceBuffer error:', err);
                        processQueue();
                    });

                    const reader = response.body.getReader();

                    try {
                        while (true) {
                            const { done, value } = await reader.read();
                            if (isDisposed) break;

                            if (done) {
                                streamDone = true;
                                processQueue();
                                break;
                            }

                            if (value && value.byteLength > 0) {
                                chunkQueue.push(value);
                                processQueue();
                            }
                        }
                    } catch (readErr) {
                        if (!isDisposed && readErr && readErr.name !== 'AbortError') {
                            console.warn('Audio stream read error:', readErr);
                        }
                    }
                }, { once: true });

                return true;
            } else {
                // Fallback for browsers without MediaSource audio/mpeg support
                const blob = await response.blob();
                const blobUrl = URL.createObjectURL(blob);
                this.audioPlayer.src = blobUrl;
                this.audioPlayer.playbackRate = this.rate;
                this.audioPlayer.volume = 1.0;
                this.audioPlayer.muted = false;
                await this.audioPlayer.play();
                return true;
            }
        } catch (error) {
            if (error && error.name === 'AbortError') {
                return false;
            }
            console.warn('Audio stream error:', error);
            this.handleSpeechFinish();
            return false;
        }
    }

    speak(text, audioSource, audioStreamUrl = null, accessToken = '') {
        if (audioStreamUrl) {
            return this.playStream(audioStreamUrl, text, accessToken);
        }
        return this.playBackendAudio(audioSource, text);
    }

    stopSpeaking() {
        if (this.currentStreamController) {
            try { this.currentStreamController.abort(); } catch {}
            this.currentStreamController = null;
        }
        if (this.audioPlayer && !this.audioPlayer.paused) this.audioPlayer.pause();
        if (this.audioPlayer) {
            this.audioPlayer.currentTime = 0;
            this.audioPlayer.volume = 1.0;
            this.audioPlayer.muted = false;
        }
        if (this.isSpeaking) {
            this.isSpeaking = false;
            this.updateSpeakingUI(false);
        }
    }

    streamSubtitles(text) {
        if (!this.subtitleElement || !text) return;
        window.clearInterval(this.subtitleTimer);
        const words = String(text).split(/\s+/);
        const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        if (reducedMotion || words.length < 5) {
            this.subtitleElement.textContent = text;
            return;
        }
        let cursor = 0;
        this.subtitleElement.textContent = '';
        this.subtitleTimer = window.setInterval(() => {
            cursor = Math.min(words.length, cursor + 3);
            this.subtitleElement.textContent = words.slice(0, cursor).join(' ');
            if (cursor >= words.length) window.clearInterval(this.subtitleTimer);
        }, 70);
    }
}

window.VoiceEngine = VoiceEngine;
